library(deSolve)
library(igraph)
library(R.matlab)
library(rmatio)
library(ggplot2)
library(stats)
library(gtools)
library(GGally)
library(network)
library(sna)
library(intergraph)
library(RColorBrewer)
#library(ggraph)
library(hashmap)
library(plyr)
library(RConics)
library(reshape2)
library(NLRoot)
library(VGAM)
library(pracma)
library(tidyverse)
library(matrixStats)
library(oce)

par(mar = rep(2, 4))

